name: "BUILD ANDROID & IOS "
on:
  push:
    branches:
      - master
      - develop
      - feature/CI

jobs:
  # Build job
  build_ios:
    name: Build IOS
    runs-on: macos-latest
    steps:
    - name: Get Branch Name 
      id: branch 
      run: echo "branch=vcl" >> $BRANCH_NAME

    - uses: haya14busa/action-cond@v1
      id: condval
      with:
        cond: ${{ steps.branch.outputs.branch == 'develop' }}
        if_true: "value for developdevelopdevelopdevelopdevelop request event"
        if_false: "value for not notnote pull request event"
    - name: Use conditional value
      run: echo "${{ steps.condval.outputs.value }} --- - - ${$BRANCH_NAME} "

